services:
  - type: web
    name: eventops-event-support-system
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /
    envVars:
      - key: DB_URL
        fromDatabase:
          name: eventops-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: eventops-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: eventops-db
          property: password

databases:
  - name: eventops-db
    databaseName: event_support_db
    user: eventops_user
    plan: free